import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          {/* Add head meta tags, styles, or fonts here */}
        </head>
        <body>
          {/* area header */}
          <header>
            <img
              width={400}
              height={60}
              src={"/images/logo-tekno.png"}
              alt="logo-tekno"
            />
          </header>

          {/* area content */}
          <section className="m-10">{children}</section>

          {/* area footer */}
          <footer className="text-center">
            Copyright &copy; 2025 - IF 22 DX
          </footer>
        </body>
      </html>
    </>
  );
}
